
base_url = "/"
content_dir = "./pages"
output_dir = "./output"
templates_dir = "./templates"

[site]
title = "Hastie Documentation"
description = "Documentation (and example) site for Hastie"
author = "Marcus Kazmierczak"
rss = true

# TODO: static dir
