repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.251
    hooks:
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.1'
    hooks:
    -   id: mypy
