
# Hastie directories
content_dir = "./pages"
output_dir = "./output"
templates_dir = "./templates"

[site]
title = "Hastie Docs"
description = "Documentation (and example) site for Hastie"
author = "Marcus Kazmierczak"

# We don't need RSS for docs, but this is what you would
# use to generate RSS for your site
# rss = true

# base url for GitHub pages
# https://mkaz.github.io/hastie/
baseurl = "/hastie"
